### ISSUE TITLE
Page Refresh (Notifications):

### ISSUE THREAD

**Issue by cpvandehey** [BabylonianTeam/Babylonians#46]
### Description:

Throughout the app, the pages don't refresh upon content change involving uploads. For instance, uploading photos to a class or changing a profile picture results in a backend change, however, the app doesnt give any notification or sign of the photo change.
### Severity

I would consider the severity of this issue to be a "blocker" because of the user confusion. A user isn't sure if their actions are completed.
### Suggestions

Add a listener to the app that can detect a database sync and would refresh a page.

**Comment by wandonye** [comment]
the tester seems confused about how app works with how web app works. there isn't a thing called refresh the page. if you mean reload the data, please check the codes: we surely have listener to handle the uploading of photo, and reload the tableviews, otherwise how do you think the photos in the course were added?
the only way I can make some sense of this bug report is possibly the tester cannot wait for a second to see the photo being uploaded and ignored the network traffic sign on the top left corner.
